# Site settings
title: Blarg
email: patthropus@gmail.com
description: "Just some bullshit for now."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: redcarpet
permalink: pretty
timezone: America/New_York

