# Site settings
title: letters, punctuation, and words
email: patthropus@gmail.com
description: "A variety of letters, punctuation, and words that sometimes form coherent sentences, and sometimes paragraphs."
baseurl: "http://blog.theystudios.org"
url: "http://blog.theystudios.org"

# Build settings
markdown: redcarpet
permalink: pretty
timezone: America/New_York

# Minifier settings
jekyll-press:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options

